author: nuno.aguiar@wedotechnologies.com
scripts:
  posterase: ''
  postinstall: 'print(''AFPing: Since version 20160616 first parameter became URL.'');'
  preerase: ''
  preinstall: ''
keywords:
  - nattrmon
  - attribute
  - monitor
  - attrmon
bugs:
  url: 'https://github.com/OpenAF/nAttrMon/issues'
repository:
  type: http
  url: 'https://raw.githubusercontent.com/OpenAF/nAttrMon/master'
description: Tool for RAID and solution functional monitoring.
name: nAttrMon
main: nattrmon.js
mainJob: ''
license: Apache 2.0 license
version: '20171116'
dependencies:
  openaf: '>=20170901'
files:
  - util/backupConfig.yaml
  - util/loadDB2Elastic.js
  - util/clean.yaml
  - config/objects.assets/noutputhttp/index.html
  - config/objects.assets/noutputhttp/now.html
  - config/objects.assets/noutputhttp/css/bootstrap.min.css
  - config/objects.assets/noutputhttp/css/nattrmon.css
  - config/objects.assets/noutputhttp/css/font-awesome.min.css
  - config/objects.assets/noutputhttp/css/bootstrap-theme.min.css
  - config/objects.assets/noutputhttp/js/angular.min.js
  - config/objects.assets/noutputhttp/js/nattrmon_js.js
  - config/objects.assets/noutputhttp/js/retina.min.js
  - config/objects.assets/noutputhttp/js/ie10-viewport-bug-workaround.js
  - config/objects.assets/noutputhttp/js/jquery.min.js
  - config/objects.assets/noutputhttp/js/bootstrap.min.js
  - config/objects.assets/noutputhttp/js/holder.min.js
  - config/objects.assets/noutputhttp/js/angular-animate.min.js
  - config/objects.assets/noutputhttp/dashboard.css
  - config/objects.assets/noutputhttp/history.html
  - config/objects.assets/noutputhttp/fonts/fontawesome-webfont.svg
  - config/objects.assets/noutputhttp/fonts/FontAwesome.otf
  - config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.woff
  - config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.eot
  - config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.ttf
  - config/objects.assets/noutputhttp/fonts/fontawesome-webfont.woff2
  - config/objects.assets/noutputhttp/fonts/fontawesome-webfont.ttf
  - config/objects.assets/noutputhttp/fonts/fontawesome-webfont.woff
  - config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.svg
  - config/objects.assets/noutputhttp/fonts/fontawesome-webfont.eot
  - config/nattrmon.lvals.snapshot
  - config/inputs.disabled/js/00.init.js
  - config/inputs.disabled/js/11.OSInfo.js
  - config/inputs.disabled/js/41.fms.rulestatus.js
  - config/inputs.disabled/js/09.filesystemcount.js
  - config/inputs.disabled/js/10.filesystem.js
  - config/inputs.disabled/js/00.doc.js
  - config/inputs.disabled/js/13.ListDirFiles.js
  - config/inputs.disabled/js/12.ShellCmd.js
  - config/inputs.disabled/js/05.filesystemCount.js
  - config/inputs.disabled/js/22.fraud.snapshots.js
  - config/inputs.disabled/js/07.logErrorAgg.js
  - config/inputs.disabled/js/10.filesystemcount.js
  - config/inputs.disabled/yaml/01.ping.yaml
  - config/inputs.disabled/yaml/10.filesystem.yaml
  - config/inputs.disabled/yaml/04.db.appadm.yaml
  - config/inputs.disabled/yaml/12.shellCmd.yaml
  - config/inputs.disabled/yaml/10.filesystemcount.mobsubscribers.yaml
  - config/inputs.disabled/yaml/10.sessions.yaml
  - config/inputs.disabled/yaml/02.test.yaml
  - config/inputs.disabled/yaml/10.osinfo.yaml
  - config/inputs.disabled/yaml/03.semaphores.yaml
  - config/inputs.disabled/yaml/10.filesystemcount.fixed.yaml
  - config/inputs.disabled/yaml/09.memory.yaml
  - config/inputs.disabled/yaml/01.test.yaml
  - config/inputs.disabled/yaml/11.times.yaml
  - config/inputs.disabled/yaml/12.connections.yaml
  - config/objects/nInput_OSInfo.js
  - config/objects/nOutput_EmailWarnings.js
  - config/objects/nOutput_H2.js
  - config/objects/nInput_Semaphores.js
  - config/objects/nOutput_Stdout.js
  - config/objects/nInput_Filesystem.js
  - config/objects/nOutput_Channels.js
  - config/objects/nInput_RAIDMemory.js
  - config/objects/nInput_AFPing.js
  - config/objects/nOutput_HTTP_JSON.js
  - config/objects/nInput_FMSRuleStatus.js
  - config/objects/nValidation_Semaphores.js
  - config/objects/nInput_Sessions.js
  - config/objects/nOutput_Oracle.js
  - config/objects/nOutput_Log.js
  - config/objects/nInput_FilesystemCount.js
  - config/objects/nValidation_AFPing.js
  - config/objects/nOutput_HTTP.js
  - config/objects/nValidation_Yellows.js
  - config/objects/nInput_RunningFlows.js
  - config/objects/nInput_LogErrorAgg.js
  - config/objects/nInput_IMMemory.js
  - config/objects/nInput_CBPMSemaphores.js
  - config/objects/nInput_Shell.js
  - config/objects/nInput_DB.js
  - config/nattrmon.attrs.snapshot
  - config/validations/add_files_from_validations_disabled.dummy
  - config/validations.disabled/js/01.validatePing.js
  - config/validations.disabled/js/30.validateYellows.js
  - config/validations.disabled/js/03.validateSemaphores.js
  - config/validations.disabled/js/04.validateErrorFlows.js
  - config/validations.disabled/yaml/01.somebodyTouched.yaml
  - config/nattrmon.cvals.snapshot
  - config/outputs.disabled/2.httpjson.js
  - config/outputs.disabled/00.init.js
  - config/outputs.disabled/3.http.js
  - config/outputs.disabled/1.oracleoutput.js
  - config/outputs.disabled/5.emailWarnings.js
  - config/outputs.disabled/yaml/09.channels.yaml
  - config/outputs.disabled/yaml/02.httpjson.yaml
  - config/outputs.disabled/4.logFile.js
  - config/outputs.disabled/1.h2output.js
  - config/outputs.disabled/9.channels.js
  - config/outputs/add_files_from_outputs_disabled.dummy
  - config/outputs/09.channels.yaml
  - config/outputs/02.httpjson.yaml
  - config/move_files_from_the_disabled_folders.dummy
  - config/inputs/add_files_from_inputs_disabled.dummy
  - config/inputs/12.shellCmd.yaml
  - .package.yaml
  - tests/nattrmonTester.js
  - tests/outputTest.yml
  - tests/unitTest.js
  - tests/inputDBTest.yml
  - tests/inputShellTest.yml
  - tests/unitTestYAML.js
  - README.md
  - .gitignore
  - lib/nattributes.js
  - lib/nattributevalue.js
  - lib/nwarnings.js
  - lib/nwarning.js
  - lib/nattribute.js
  - lib/nplug.js
  - lib/ninput.js
  - lib/nvalidation.js
  - lib/nmonitoredobject.js
  - lib/noutput.js
  - nattrmon.js
filesHash:
  util/backupConfig.yaml: 55d5cfebaf1acb87bd9ce2523015608b03f586e1
  util/loadDB2Elastic.js: 190b68c03e71fa859df71429da4c31035f20ce94
  util/clean.yaml: 5e41d1c1362288e1a77201cca379997288a89290
  config/objects.assets/noutputhttp/index.html: c454af426dc25960d1a2992b6cac99e11881ea48
  config/objects.assets/noutputhttp/now.html: 8dc28c8f998a319561567c342aa46fc16974e459
  config/objects.assets/noutputhttp/css/bootstrap.min.css: ed29315e0ffb3f14382431f2724235bf67f44eb3
  config/objects.assets/noutputhttp/css/nattrmon.css: aae10531cb3de16311f0ecc9f5bb213b5a3ac80c
  config/objects.assets/noutputhttp/css/font-awesome.min.css: 05ea25bc9b3ac48993e1fee322d3bc94b49a6e22
  config/objects.assets/noutputhttp/css/bootstrap-theme.min.css: fc6b4268fbd57ad95d2b41a1d4d6866f222fbdb2
  config/objects.assets/noutputhttp/js/angular.min.js: d0e3fccc46957eeaaf5611075a2015b410b64725
  config/objects.assets/noutputhttp/js/nattrmon_js.js: 16029240edd06a1d54bf1baad40c0dbc466b3940
  config/objects.assets/noutputhttp/js/retina.min.js: da44a409a0907960a6526cf35807ecaf61059223
  config/objects.assets/noutputhttp/js/ie10-viewport-bug-workaround.js: b133cb4aaff8f32026190281d8a27456eace82b1
  config/objects.assets/noutputhttp/js/jquery.min.js: 7ed710bf2b3a08cee23950790208683b0346fb1c
  config/objects.assets/noutputhttp/js/bootstrap.min.js: 253711c6d825de55a8360552573be950da180614
  config/objects.assets/noutputhttp/js/holder.min.js: c1ad1dcfebf4c1770d40fc5d7bc46ca692d12822
  config/objects.assets/noutputhttp/js/angular-animate.min.js: 648e2ca79c0c074b2b61042e91d31b353ad290d3
  config/objects.assets/noutputhttp/dashboard.css: 96d9d77e456868b0797afe0ce344be026315d535
  config/objects.assets/noutputhttp/history.html: aac6be153b65c31424a2b0e33b772b2e129fe76b
  config/objects.assets/noutputhttp/fonts/fontawesome-webfont.svg: 2b3c8ba7008cc014d8fb37abc6f9f49aeda83824
  config/objects.assets/noutputhttp/fonts/FontAwesome.otf: 0112e96f327d413938d37c1693806f468ffdbace
  config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.woff: 278e49a86e634da6f2a02f3b47dd9d2a8f26210f
  config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.eot: 86b6f62b7853e67d3e635f6512a5a5efc58ea3c3
  config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.ttf: 44bc1850f570972267b169ae18f1cb06b611ffa2
  config/objects.assets/noutputhttp/fonts/fontawesome-webfont.woff2: 574ea2698c03ae9477db2ea3baf460ee32f1a7ea
  config/objects.assets/noutputhttp/fonts/fontawesome-webfont.ttf: 27cf1f2ec59aece6938c7bb2feb0e287ea778ff9
  config/objects.assets/noutputhttp/fonts/fontawesome-webfont.woff: 507970402e328b2baeb05bde73bf9ded4e2c3a2d
  config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.svg: de51a8494180a6db074af2dee2383f0a363c5b08
  config/objects.assets/noutputhttp/fonts/fontawesome-webfont.eot: b3c2f08e73320135b69c23a3908b87a12053a2f6
  config/inputs.disabled/js/00.init.js: 0156834a9dd44c3685f2de871a6c84f78d631fa5
  config/inputs.disabled/js/11.OSInfo.js: ff6d21332af1722b09a3cce062876a1b5e5b0eef
  config/inputs.disabled/js/41.fms.rulestatus.js: 5b3012d798f11d2c82a633b3e54f5d6dc53614ad
  config/inputs.disabled/js/09.filesystemcount.js: 21ae3c36036bfaa0f786e73e9e862978727401df
  config/inputs.disabled/js/10.filesystem.js: 23a492c93be89b7be4163169f581c28dd85ab502
  config/inputs.disabled/js/00.doc.js: f03eb7b9bd36452d412d3668b0a4ef9c7605de65
  config/inputs.disabled/js/13.ListDirFiles.js: 9ba182a6d286e5ac284828f24cb40ced8d36f0b9
  config/inputs.disabled/js/12.ShellCmd.js: eba2f60ed7c7e14a7340bd25fa8720eb1d12c026
  config/inputs.disabled/js/05.filesystemCount.js: 1a75ceb882dc94b03b9f05f696a7292cc9216ca3
  config/inputs.disabled/js/22.fraud.snapshots.js: eb5d52a7b57dece7331c2c9bbe612bc8cda8433e
  config/inputs.disabled/js/07.logErrorAgg.js: 924ca27ea2017cefa6550810bfcf216652597180
  config/inputs.disabled/js/10.filesystemcount.js: a1ae5183c585f082779e403c5f4b87dcc2c3a0f6
  config/inputs.disabled/yaml/01.ping.yaml: 150623bdda84b0533f68101d737bb70b95d60564
  config/inputs.disabled/yaml/10.filesystem.yaml: 8bb13a7aa3c03e9e0f613d3515401ee5d6f142f9
  config/inputs.disabled/yaml/04.db.appadm.yaml: eb7276a6f29f772b17fa18b33dc43a8d36888e9a
  config/inputs.disabled/yaml/12.shellCmd.yaml: 30be1c8b7f3c0b2c9a089b6ea5d69e58413e8e98
  config/inputs.disabled/yaml/10.filesystemcount.mobsubscribers.yaml: 99dc4af0fab8d6560cb7d6b84d84e7ab22f580a5
  config/inputs.disabled/yaml/10.sessions.yaml: a90fbe001094e39379e97b2cb86423312bfb150f
  config/inputs.disabled/yaml/02.test.yaml: 51909f83080e7066bd6070511f54bab95c2b3f21
  config/inputs.disabled/yaml/10.osinfo.yaml: 6b4782f7a307e447bb5ac9361da50ff0061029e0
  config/inputs.disabled/yaml/03.semaphores.yaml: c316d3ad7cacfd139dc49b34bdf1729dd80e25ba
  config/inputs.disabled/yaml/10.filesystemcount.fixed.yaml: 1faa5c67efd1210e3905408f42a4e65ea96d3781
  config/inputs.disabled/yaml/09.memory.yaml: 3158d18d05c8b987aff741209337708945ec54a3
  config/inputs.disabled/yaml/01.test.yaml: 4052b24ab16c69c0ff87c791f9fe3d8e46738c3e
  config/inputs.disabled/yaml/11.times.yaml: bf46ace095f1674743ed938e3a740f6e1990ff8e
  config/inputs.disabled/yaml/12.connections.yaml: de116141e7057146059a8e7afd5081185f0602fc
  config/objects/nInput_OSInfo.js: 3418957f8d9e4d47dba8dd1100d0d101337904b3
  config/objects/nOutput_EmailWarnings.js: efde17d1a4704319a2783e4995c3643e06d5f232
  config/objects/nOutput_H2.js: 9f231c207510afc896de968eee3bdc3db558dd77
  config/objects/nInput_Semaphores.js: d837eae50410502438f9d2671bb5d52fb493e42b
  config/objects/nOutput_Stdout.js: 5a0d72c32e2f969fe3e27cbad64c7ccf0959aad1
  config/objects/nInput_Filesystem.js: 4117c1a9b19df25d80ce23b69782ff85bd131da7
  config/objects/nOutput_Channels.js: 3ac54c980da17ebb66f044cef56dd16b32a70e0e
  config/objects/nInput_RAIDMemory.js: 69c531663d40f275b071dd0a7d428f49e52ba6f5
  config/objects/nInput_AFPing.js: 04258ea17b7063a79e125169b7577faa000a7117
  config/objects/nOutput_HTTP_JSON.js: 047a7086b8fd58ede9029a6832736de2e7c639cd
  config/objects/nInput_FMSRuleStatus.js: a5e4f9a505865b394a81ae4bbbdd839c91d07902
  config/objects/nValidation_Semaphores.js: 97b6c1850b80d95cc92c1c50b05fdfa26467fd94
  config/objects/nInput_Sessions.js: 7c2d89a027fe0fa6478ab491484ce0d79fe27651
  config/objects/nOutput_Oracle.js: 93fa7228120945b1f1f6a7ecd8cf17853a4c6966
  config/objects/nOutput_Log.js: 2a1d2d88a54b31b0fa1cece340c4a95ce8888476
  config/objects/nInput_FilesystemCount.js: daf3bd9806156dd16a0ac19692290d8b720fc0f9
  config/objects/nValidation_AFPing.js: f7ce653012d15558088e50458adc415fa9792eaa
  config/objects/nOutput_HTTP.js: 91453206bd740cb62fc2807e14b424de0110db2c
  config/objects/nValidation_Yellows.js: 942478fcd710e392add0b6ef6349ef51a895b764
  config/objects/nInput_RunningFlows.js: f21d3f64fc10348a5f7297aeae439c25bc5c68f0
  config/objects/nInput_LogErrorAgg.js: 149f6b0a61a806a0d3ffcf2975bb151f0a94317f
  config/objects/nInput_IMMemory.js: 1b3570cb3c64005c6b731f837c0684cd22cb5403
  config/objects/nInput_CBPMSemaphores.js: e22546f3b1de2b17d959c0fdbf0a35ea644c78ad
  config/objects/nInput_Shell.js: de4e651212ce678428caaa606fcec129b89a03bc
  config/objects/nInput_DB.js: 80437eeca4353ae8675bf9c35dba6a83bcf478ef
  config/validations/add_files_from_validations_disabled.dummy: da39a3ee5e6b4b0d3255bfef95601890afd80709
  config/validations.disabled/js/01.validatePing.js: cc572c157971ebdccd0a40a261f199cb9e509b5c
  config/validations.disabled/js/30.validateYellows.js: 7a99fcd5e3728805783c5c18aff97488f3aed5d7
  config/validations.disabled/js/03.validateSemaphores.js: 6ded3ea530db8b5d4621fa8bad510e281ebd632d
  config/validations.disabled/js/04.validateErrorFlows.js: 9b7ff4c1cd03fe47082107d2c22250be1d45a2b4
  config/validations.disabled/yaml/01.somebodyTouched.yaml: 2d6a2c34c39aec49d9126c6304e04e66b978a26a
  config/outputs.disabled/2.httpjson.js: f59875492834d2b24895bae73b51dfef3c38f49b
  config/outputs.disabled/00.init.js: 71ba0fb4fffa284500e9deb90213bfed66134568
  config/outputs.disabled/3.http.js: 2c330262e3580992b79cacd0514bb2cdc6d1e17e
  config/outputs.disabled/1.oracleoutput.js: 0f7ce56148ba6772216ce4402f5509077c30af6e
  config/outputs.disabled/5.emailWarnings.js: 4a0139aabd64a3c56c1842499dd6d2203f607550
  config/outputs.disabled/yaml/09.channels.yaml: 5149e2ecb9fbb0884fe37dbb6e8ff6a0bd05243d
  config/outputs.disabled/yaml/02.httpjson.yaml: 7c47a8c640dc9d8b8de10089ff2b90785d4eab9a
  config/outputs.disabled/4.logFile.js: 00ee44fa9c934d02beb6ec62b1aff6c473c14dbb
  config/outputs.disabled/1.h2output.js: a2dce3c2e443ca52f3344aca3529a17a064b3a51
  config/outputs.disabled/9.channels.js: b57f0fe5f21d37e936f14031d439cfa48ca9c06b
  config/outputs/add_files_from_outputs_disabled.dummy: da39a3ee5e6b4b0d3255bfef95601890afd80709
  config/move_files_from_the_disabled_folders.dummy: da39a3ee5e6b4b0d3255bfef95601890afd80709
  config/inputs/add_files_from_inputs_disabled.dummy: da39a3ee5e6b4b0d3255bfef95601890afd80709
  tests/nattrmonTester.js: 228472c2b83fbc11688a6d25a0d97165f78b4883
  tests/outputTest.yml: 0c4ba4176163e4aa9ff7fd4ae4128339d8384581
  tests/unitTest.js: 067565f7c1517b331684246f5c9a7949124417ea
  tests/inputDBTest.yml: c38616606dc5956e449189d11f8e661170f94dfb
  tests/inputShellTest.yml: ce643955982cb16b53a8843acd3549466e5cddf5
  tests/unitTestYAML.js: 215400bf5e21fbb27f507c2e10b1e75f290e8ff2
  README.md: 648ce4e29bbdc7b99f5cf8734cb1a7f0657789c7
  lib/nattributes.js: 35aa5c0dbda964c43dcf1d1b755d642f49d2d272
  lib/nattributevalue.js: d69fff1f7ac29257416ddf4f1eb91e100db9d80e
  lib/nwarnings.js: 616a2c5d9c1f8800d5550c43506fe872ef97b69a
  lib/nwarning.js: 55c0098921b17633f3c97b262ade18630f54f8cf
  lib/nattribute.js: 841e00c3a111133e3d103ef6e24885feb2965108
  lib/nplug.js: 51f921822b4195de6cd949ea443c79fd64dce18b
  lib/ninput.js: 4e7b45bb7dc92950f64451d17a30859d4c4f10e2
  lib/nvalidation.js: 7cc4d548de8af9ee7924b549f6304c1be2bc7f36
  lib/nmonitoredobject.js: da0b8a8590ce1534826750e2e70b3d6e4bee9f98
  lib/noutput.js: 0ee871777643fb7f59aa2274f202a721bc500bea
  nattrmon.js: 3d80ee60a49be0347ac3fdcae86de31757dcda6b
