author: Nuno Aguiar
scripts:
  posterase: ''
  postinstall: ''
  preerase: ''
  preinstall: ''
keywords:
  - nattrmon
  - attribute
  - monitor
  - attrmon
bugs:
  url: 'https://github.com/OpenAF/nAttrMon/issues'
repository:
  type: http
  url: 'https://raw.githubusercontent.com/OpenAF/nAttrMon/master'
description: Tool for RAID and solution functional monitoring.
name: nAttrMon
main: nattrmon.js
mainJob: ''
license: Apache 2.0 license
version: '20180205'
dependencies:
  openaf: '>=20180130'
files:
  - .gitignore
  - .package.yaml
  - config/inputs/add_files_from_inputs_disabled.dummy
  - config/inputs.disabled/js/00.doc.js
  - config/inputs.disabled/js/00.init.js
  - config/inputs.disabled/js/05.filesystemCount.js
  - config/inputs.disabled/js/07.logErrorAgg.js
  - config/inputs.disabled/js/09.filesystemcount.js
  - config/inputs.disabled/js/10.filesystem.js
  - config/inputs.disabled/js/10.filesystemcount.js
  - config/inputs.disabled/js/11.OSInfo.js
  - config/inputs.disabled/js/12.ShellCmd.js
  - config/inputs.disabled/js/13.ListDirFiles.js
  - config/inputs.disabled/js/22.fraud.snapshots.js
  - config/inputs.disabled/js/41.fms.rulestatus.js
  - config/inputs.disabled/yaml/01.ping.yaml
  - config/inputs.disabled/yaml/01.test.yaml
  - config/inputs.disabled/yaml/02.test.yaml
  - config/inputs.disabled/yaml/03.semaphores.yaml
  - config/inputs.disabled/yaml/04.db.appadm.yaml
  - config/inputs.disabled/yaml/09.memory.yaml
  - config/inputs.disabled/yaml/10.filesystem.yaml
  - config/inputs.disabled/yaml/10.filesystemcount.fixed.yaml
  - config/inputs.disabled/yaml/10.filesystemcount.mobsubscribers.yaml
  - config/inputs.disabled/yaml/10.osinfo.yaml
  - config/inputs.disabled/yaml/10.sessions.yaml
  - config/inputs.disabled/yaml/11.times.yaml
  - config/inputs.disabled/yaml/12.connections.yaml
  - config/inputs.disabled/yaml/12.shellCmd.yaml
  - config/move_files_from_the_disabled_folders.dummy
  - config/objects/nInput_AFPing.js
  - config/objects/nInput_CBPMSemaphores.js
  - config/objects/nInput_DB.js
  - config/objects/nInput_EndPoints.js
  - config/objects/nInput_Filesystem.js
  - config/objects/nInput_FilesystemCount.js
  - config/objects/nInput_FMSRuleStatus.js
  - config/objects/nInput_IMMemory.js
  - config/objects/nInput_LogErrorAgg.js
  - config/objects/nInput_OSInfo.js
  - config/objects/nInput_RAIDMemory.js
  - config/objects/nInput_RunningFlows.js
  - config/objects/nInput_Semaphores.js
  - config/objects/nInput_Sessions.js
  - config/objects/nInput_Shell.js
  - config/objects/nOutput_Channels.js
  - config/objects/nOutput_EmailWarnings.js
  - config/objects/nOutput_H2.js
  - config/objects/nOutput_HTTP.js
  - config/objects/nOutput_HTTP_JSON.js
  - config/objects/nOutput_Log.js
  - config/objects/nOutput_Notifications.js
  - config/objects/nOutput_Oracle.js
  - config/objects/nOutput_Stdout.js
  - config/objects/nValidation_AFPing.js
  - config/objects/nValidation_Generic.js
  - config/objects/nValidation_Semaphores.js
  - config/objects/nValidation_Yellows.js
  - config/objects.assets/noutputemailwarnings/logo.png
  - config/objects.assets/noutputemailwarnings/warningEmailTemplate.hbs
  - config/objects.assets/noutputhttp/css/bootstrap-theme.min.css
  - config/objects.assets/noutputhttp/css/bootstrap.min.css
  - config/objects.assets/noutputhttp/css/font-awesome.min.css
  - config/objects.assets/noutputhttp/css/nattrmon.css
  - config/objects.assets/noutputhttp/dashboard.css
  - config/objects.assets/noutputhttp/favicon.png
  - config/objects.assets/noutputhttp/fonts/fontawesome-webfont.eot
  - config/objects.assets/noutputhttp/fonts/fontawesome-webfont.svg
  - config/objects.assets/noutputhttp/fonts/fontawesome-webfont.ttf
  - config/objects.assets/noutputhttp/fonts/fontawesome-webfont.woff
  - config/objects.assets/noutputhttp/fonts/fontawesome-webfont.woff2
  - config/objects.assets/noutputhttp/fonts/FontAwesome.otf
  - config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.eot
  - config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.svg
  - config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.ttf
  - config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.woff
  - config/objects.assets/noutputhttp/fonts/icon.eot
  - config/objects.assets/noutputhttp/fonts/icon.svg
  - config/objects.assets/noutputhttp/fonts/icon.ttf
  - config/objects.assets/noutputhttp/fonts/icon.woff
  - config/objects.assets/noutputhttp/history.html
  - config/objects.assets/noutputhttp/index.html
  - config/objects.assets/noutputhttp/js/angular-animate.min.js
  - config/objects.assets/noutputhttp/js/angular.min.js
  - config/objects.assets/noutputhttp/js/bootstrap.min.js
  - config/objects.assets/noutputhttp/js/holder.min.js
  - config/objects.assets/noutputhttp/js/ie10-viewport-bug-workaround.js
  - config/objects.assets/noutputhttp/js/jquery.min.js
  - config/objects.assets/noutputhttp/js/nattrmon_js.js
  - config/objects.assets/noutputhttp/js/retina.min.js
  - config/objects.assets/noutputhttp/now.html
  - config/objects.assets/noutputhttp/plugs.html
  - config/outputs/add_files_from_outputs_disabled.dummy
  - config/outputs.disabled/00.init.js
  - config/outputs.disabled/1.h2output.js
  - config/outputs.disabled/1.oracleoutput.js
  - config/outputs.disabled/2.httpjson.js
  - config/outputs.disabled/3.http.js
  - config/outputs.disabled/4.logFile.js
  - config/outputs.disabled/5.emailWarnings.js
  - config/outputs.disabled/js/09.channels.js
  - config/outputs.disabled/yaml/01.h2output.yaml
  - config/outputs.disabled/yaml/02.httpjson.yaml
  - config/outputs.disabled/yaml/03.http.yaml
  - config/outputs.disabled/yaml/04.emailWarnings.yaml
  - config/outputs.disabled/yaml/09.channels.yaml
  - config/validations/add_files_from_validations_disabled.dummy
  - config/validations.disabled/js/01.validatePing.js
  - config/validations.disabled/js/03.validateSemaphores.js
  - config/validations.disabled/js/04.validateErrorFlows.js
  - config/validations.disabled/js/30.validateYellows.js
  - config/validations.disabled/yaml/01.somebodyTouched.yaml
  - config/validations.disabled/yaml/01.validatePing.yaml
  - lib/nattribute.js
  - lib/nattributes.js
  - lib/nattributevalue.js
  - lib/ninput.js
  - lib/nmonitoredobject.js
  - lib/noutput.js
  - lib/nplug.js
  - lib/nvalidation.js
  - lib/nwarning.js
  - lib/nwarnings.js
  - nattrmon.js
  - README.md
  - tests/inputDBTest.yml
  - tests/inputShellTest.yml
  - tests/nattrmonTester.js
  - tests/outputTest.yml
  - tests/unitTest.js
  - tests/unitTestYAML.js
  - util/backupConfig.yaml
  - util/clean.yaml
  - util/loadDB2Elastic.js
filesHash:
  .gitignore: f7206c200c6c95e6ce56afc36f29f63106f16be6
  config/inputs/add_files_from_inputs_disabled.dummy: da39a3ee5e6b4b0d3255bfef95601890afd80709
  config/inputs.disabled/js/00.doc.js: f03eb7b9bd36452d412d3668b0a4ef9c7605de65
  config/inputs.disabled/js/00.init.js: 0156834a9dd44c3685f2de871a6c84f78d631fa5
  config/inputs.disabled/js/05.filesystemCount.js: 1a75ceb882dc94b03b9f05f696a7292cc9216ca3
  config/inputs.disabled/js/07.logErrorAgg.js: 924ca27ea2017cefa6550810bfcf216652597180
  config/inputs.disabled/js/09.filesystemcount.js: 21ae3c36036bfaa0f786e73e9e862978727401df
  config/inputs.disabled/js/10.filesystem.js: 23a492c93be89b7be4163169f581c28dd85ab502
  config/inputs.disabled/js/10.filesystemcount.js: a1ae5183c585f082779e403c5f4b87dcc2c3a0f6
  config/inputs.disabled/js/11.OSInfo.js: ff6d21332af1722b09a3cce062876a1b5e5b0eef
  config/inputs.disabled/js/12.ShellCmd.js: eba2f60ed7c7e14a7340bd25fa8720eb1d12c026
  config/inputs.disabled/js/13.ListDirFiles.js: a5553247493a4039839d584c5cf590765429f3e2
  config/inputs.disabled/js/22.fraud.snapshots.js: eb5d52a7b57dece7331c2c9bbe612bc8cda8433e
  config/inputs.disabled/js/41.fms.rulestatus.js: 5b3012d798f11d2c82a633b3e54f5d6dc53614ad
  config/inputs.disabled/yaml/01.ping.yaml: 9ba4d3140e53cc501f2fe8def5cbe42e96c61331
  config/inputs.disabled/yaml/01.test.yaml: 9da08f1b20136cfc092f37b386810ce7497ba509
  config/inputs.disabled/yaml/02.test.yaml: c67b289f6fb904cbf0167908b8af3a39780879b7
  config/inputs.disabled/yaml/03.semaphores.yaml: 1c261bc2608c062f7e2299c7c0166d4548c7cf88
  config/inputs.disabled/yaml/04.db.appadm.yaml: 92a832c9ff134246aa889e2702f21085e28ccfda
  config/inputs.disabled/yaml/09.memory.yaml: f79360180738e0851b9bccbbdae1b6a7bccd052e
  config/inputs.disabled/yaml/10.filesystem.yaml: 3bc5c83e08464f9789f42161801fef768c7f2f3b
  config/inputs.disabled/yaml/10.filesystemcount.fixed.yaml: 168a63748db3a66fffeaa3e8c518e2ae4f123de4
  config/inputs.disabled/yaml/10.filesystemcount.mobsubscribers.yaml: 9996683cf2ba934c2b0dd2790ab953d7a05d6020
  config/inputs.disabled/yaml/10.osinfo.yaml: da7b6da3e3662b77917ccba2ebb008e36cdf89d6
  config/inputs.disabled/yaml/10.sessions.yaml: 94c2ae34e45bf31f7efd979bddb60ac90348e2a3
  config/inputs.disabled/yaml/11.times.yaml: 0d2c1bfb7bd2f3160840b9aad98cd03e1cf68080
  config/inputs.disabled/yaml/12.connections.yaml: 691345117ddd695b5493127dea0a5568a8283fe9
  config/inputs.disabled/yaml/12.shellCmd.yaml: 0add6dbaa328f63e3ad864db9686bd98e1b3c2cf
  config/move_files_from_the_disabled_folders.dummy: da39a3ee5e6b4b0d3255bfef95601890afd80709
  config/objects/nInput_AFPing.js: fb1405a486d3a627488f746b791c373579c3a6bc
  config/objects/nInput_CBPMSemaphores.js: e22546f3b1de2b17d959c0fdbf0a35ea644c78ad
  config/objects/nInput_DB.js: 380121087bc0d77e18ffa0e9c9cc689c058ce184
  config/objects/nInput_EndPoints.js: 03084acddad1d42bd447ab5890dadac629681f96
  config/objects/nInput_Filesystem.js: 4117c1a9b19df25d80ce23b69782ff85bd131da7
  config/objects/nInput_FilesystemCount.js: daf3bd9806156dd16a0ac19692290d8b720fc0f9
  config/objects/nInput_FMSRuleStatus.js: a5e4f9a505865b394a81ae4bbbdd839c91d07902
  config/objects/nInput_IMMemory.js: 1b3570cb3c64005c6b731f837c0684cd22cb5403
  config/objects/nInput_LogErrorAgg.js: 29b9201607432b841f41871a83475d9a25409215
  config/objects/nInput_OSInfo.js: 3418957f8d9e4d47dba8dd1100d0d101337904b3
  config/objects/nInput_RAIDMemory.js: bf7945d3af630132abf94f737524f38b8a4f74bd
  config/objects/nInput_RunningFlows.js: 578e1d231ee304d5b86f569e31f5ea95b04bccfd
  config/objects/nInput_Semaphores.js: f7dbeabb7e1baebef64fa09a9a9fd68e59026aa2
  config/objects/nInput_Sessions.js: 0a68a945ba6c4b98d139b8c666c275c4fc716f81
  config/objects/nInput_Shell.js: de4e651212ce678428caaa606fcec129b89a03bc
  config/objects/nOutput_Channels.js: 02f48d8ff9f9a281fcd488869169cbb730209133
  config/objects/nOutput_EmailWarnings.js: 76a45f64096a2d645d623aead790726d01419326
  config/objects/nOutput_H2.js: d4b2182a8acf34caf4408be7048826915511ccf2
  config/objects/nOutput_HTTP.js: e0e365cd54a8e70729f1076899c5009422a004ab
  config/objects/nOutput_HTTP_JSON.js: a8f33d05e5a7f33e6d97ce5096b7906f63d31787
  config/objects/nOutput_Log.js: 2a1d2d88a54b31b0fa1cece340c4a95ce8888476
  config/objects/nOutput_Notifications.js: 53c73cac46e6bd99de0e8ec5bf6a7ca63590ff5e
  config/objects/nOutput_Oracle.js: ab0f2fe7958952437ae93030715633858462269f
  config/objects/nOutput_Stdout.js: 5a0d72c32e2f969fe3e27cbad64c7ccf0959aad1
  config/objects/nValidation_AFPing.js: f48325d605e693dee3ab2912224cda0fde11e490
  config/objects/nValidation_Generic.js: 96bd3656e884a498451c83b25ebfdd6f1083d2f1
  config/objects/nValidation_Semaphores.js: 97b6c1850b80d95cc92c1c50b05fdfa26467fd94
  config/objects/nValidation_Yellows.js: 942478fcd710e392add0b6ef6349ef51a895b764
  config/objects.assets/noutputemailwarnings/logo.png: ee5366a3aa207c69d5139e04e7a4523078b974ba
  config/objects.assets/noutputemailwarnings/warningEmailTemplate.hbs: e5913675ad5adf1bd217a15de9148c65e39f3822
  config/objects.assets/noutputhttp/css/bootstrap-theme.min.css: c277f5dc2e08fa885e401ee367ac6c0eefa7a6dc
  config/objects.assets/noutputhttp/css/bootstrap.min.css: 12028adaae10f0c43445362df5481aeec8bb1153
  config/objects.assets/noutputhttp/css/font-awesome.min.css: 4c2c5f5f6cc86d775a44b944661e038b7be98149
  config/objects.assets/noutputhttp/css/nattrmon.css: d7d83aa0d973efa4c78b6b9a40f25863e2732563
  config/objects.assets/noutputhttp/dashboard.css: 96d9d77e456868b0797afe0ce344be026315d535
  config/objects.assets/noutputhttp/favicon.png: 1ad74b6b72424d71c71da6f832ca8f4e7ac5d632
  config/objects.assets/noutputhttp/fonts/fontawesome-webfont.eot: b3c2f08e73320135b69c23a3908b87a12053a2f6
  config/objects.assets/noutputhttp/fonts/fontawesome-webfont.svg: f346b8b3df147e4059e1a7d66c52c9a6e1cec3e8
  config/objects.assets/noutputhttp/fonts/fontawesome-webfont.ttf: 27cf1f2ec59aece6938c7bb2feb0e287ea778ff9
  config/objects.assets/noutputhttp/fonts/fontawesome-webfont.woff: 507970402e328b2baeb05bde73bf9ded4e2c3a2d
  config/objects.assets/noutputhttp/fonts/fontawesome-webfont.woff2: 574ea2698c03ae9477db2ea3baf460ee32f1a7ea
  config/objects.assets/noutputhttp/fonts/FontAwesome.otf: 0112e96f327d413938d37c1693806f468ffdbace
  config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.eot: 86b6f62b7853e67d3e635f6512a5a5efc58ea3c3
  config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.svg: 4dcf0ab896f5417047f881de91bad10dcbda48c6
  config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.ttf: 44bc1850f570972267b169ae18f1cb06b611ffa2
  config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.woff: 278e49a86e634da6f2a02f3b47dd9d2a8f26210f
  config/objects.assets/noutputhttp/fonts/icon.eot: 1821dc5d05f13dc52ec7363f38258265f88202e8
  config/objects.assets/noutputhttp/fonts/icon.svg: 3890f01fd40b7ac222f232f7ee7ac9f43a249953
  config/objects.assets/noutputhttp/fonts/icon.ttf: 35f955b5810ecdddfdcf3d6c0140186882a19bdb
  config/objects.assets/noutputhttp/fonts/icon.woff: 24762bf06bbde956f97836f84d9af098f237c44f
  config/objects.assets/noutputhttp/history.html: ccb80e5a27255e40e6ca2d7c585b94adccccd91c
  config/objects.assets/noutputhttp/index.html: 1a1e34b48e68e6b88da0ca34011a6e871fd4f4ce
  config/objects.assets/noutputhttp/js/angular-animate.min.js: 648e2ca79c0c074b2b61042e91d31b353ad290d3
  config/objects.assets/noutputhttp/js/angular.min.js: d0e3fccc46957eeaaf5611075a2015b410b64725
  config/objects.assets/noutputhttp/js/bootstrap.min.js: 253711c6d825de55a8360552573be950da180614
  config/objects.assets/noutputhttp/js/holder.min.js: c1ad1dcfebf4c1770d40fc5d7bc46ca692d12822
  config/objects.assets/noutputhttp/js/ie10-viewport-bug-workaround.js: b133cb4aaff8f32026190281d8a27456eace82b1
  config/objects.assets/noutputhttp/js/jquery.min.js: 7ed710bf2b3a08cee23950790208683b0346fb1c
  config/objects.assets/noutputhttp/js/nattrmon_js.js: c926c6a8003f32bc8afcc3b6b3ed0330d5a9cc49
  config/objects.assets/noutputhttp/js/retina.min.js: da44a409a0907960a6526cf35807ecaf61059223
  config/objects.assets/noutputhttp/now.html: eaf96e43ea90311c6aa34283a264cf27a125a391
  config/objects.assets/noutputhttp/plugs.html: 362b62241ae40c3208c2fc8935d894ac8d370810
  config/outputs/add_files_from_outputs_disabled.dummy: da39a3ee5e6b4b0d3255bfef95601890afd80709
  config/outputs.disabled/00.init.js: 71ba0fb4fffa284500e9deb90213bfed66134568
  config/outputs.disabled/1.h2output.js: a2dce3c2e443ca52f3344aca3529a17a064b3a51
  config/outputs.disabled/1.oracleoutput.js: 0f7ce56148ba6772216ce4402f5509077c30af6e
  config/outputs.disabled/2.httpjson.js: f59875492834d2b24895bae73b51dfef3c38f49b
  config/outputs.disabled/3.http.js: 2c330262e3580992b79cacd0514bb2cdc6d1e17e
  config/outputs.disabled/4.logFile.js: 00ee44fa9c934d02beb6ec62b1aff6c473c14dbb
  config/outputs.disabled/5.emailWarnings.js: 4a0139aabd64a3c56c1842499dd6d2203f607550
  config/outputs.disabled/js/09.channels.js: 90b095b9c68e01b3aa724a8c370391f6d75cadf5
  config/outputs.disabled/yaml/01.h2output.yaml: 3fdb74033912b40fed818664a4df9fca2d3f7998
  config/outputs.disabled/yaml/02.httpjson.yaml: 7c47a8c640dc9d8b8de10089ff2b90785d4eab9a
  config/outputs.disabled/yaml/03.http.yaml: 3b0e03b04aea38eaf2a88c56da53d6767b899cba
  config/outputs.disabled/yaml/04.emailWarnings.yaml: 5b4705eb204fc63d2627ab3f5452fc697379568f
  config/outputs.disabled/yaml/09.channels.yaml: 99127166c4a2392fec5a0d681424bf61f68c0a95
  config/validations/add_files_from_validations_disabled.dummy: da39a3ee5e6b4b0d3255bfef95601890afd80709
  config/validations.disabled/js/01.validatePing.js: cc572c157971ebdccd0a40a261f199cb9e509b5c
  config/validations.disabled/js/03.validateSemaphores.js: 6ded3ea530db8b5d4621fa8bad510e281ebd632d
  config/validations.disabled/js/04.validateErrorFlows.js: 9b7ff4c1cd03fe47082107d2c22250be1d45a2b4
  config/validations.disabled/js/30.validateYellows.js: 7a99fcd5e3728805783c5c18aff97488f3aed5d7
  config/validations.disabled/yaml/01.somebodyTouched.yaml: 2d6a2c34c39aec49d9126c6304e04e66b978a26a
  config/validations.disabled/yaml/01.validatePing.yaml: 26a36f729f9443a1893afb7a8586fe7e396085db
  lib/nattribute.js: 0eeb6849981672a5660811fb740327e8032211f5
  lib/nattributes.js: 35aa5c0dbda964c43dcf1d1b755d642f49d2d272
  lib/nattributevalue.js: d6a378dba74922540bcc3e054222733f69d5cead
  lib/ninput.js: cb1a2bc442a0a3ac9e6237fd02b445e31bd518cf
  lib/nmonitoredobject.js: da0b8a8590ce1534826750e2e70b3d6e4bee9f98
  lib/noutput.js: 097a89ae2ab12cb28d88034444a72d368464d14c
  lib/nplug.js: 93e2ac5b530dd7501ea78b0563869cbacfc515ba
  lib/nvalidation.js: 419ebc9daa5149344d45a0563e7ae5509da1970b
  lib/nwarning.js: 3bc36903e8e7f9be49b3f65352fe1dfddbe5b2aa
  lib/nwarnings.js: d3cbf26c8e834a2151390505f3b880624ecbfc71
  nattrmon.js: 1e161289db9e9c95a610d284fc56e008bc44489c
  README.md: 648ce4e29bbdc7b99f5cf8734cb1a7f0657789c7
  tests/inputDBTest.yml: c38616606dc5956e449189d11f8e661170f94dfb
  tests/inputShellTest.yml: ce643955982cb16b53a8843acd3549466e5cddf5
  tests/nattrmonTester.js: 72d94313ed4d69f0ec39a7d353a3edc723348248
  tests/outputTest.yml: 0c4ba4176163e4aa9ff7fd4ae4128339d8384581
  tests/unitTest.js: 067565f7c1517b331684246f5c9a7949124417ea
  tests/unitTestYAML.js: 0fa75983c5b2af572891d6329fc18d10f7a47150
  util/backupConfig.yaml: f84a08a3c5c8aa50f5aa606585c1453901c20d84
  util/clean.yaml: 616b7ddb24b12af7f1cbec473282decb57843869
  util/loadDB2Elastic.js: 190b68c03e71fa859df71429da4c31035f20ce94
