author: nuno.aguiar@wedotechnologies.com
scripts:
  posterase: ''
  postinstall: 'print(''AFPing: Since version 20160616 first parameter became URL.'');'
  preerase: ''
  preinstall: ''
keywords:
  - nattrmon
  - attribute
  - monitor
  - attrmon
bugs:
  url: 'https://github.com/OpenAF/nAttrMon/issues'
repository:
  type: http
  url: 'https://raw.githubusercontent.com/OpenAF/nAttrMon/master'
description: Tool for RAID and solution functional monitoring.
name: nAttrMon
main: nattrmon.js
mainJob: ''
license: Apache 2.0 license
version: '20171102'
dependencies:
  openaf: '>=20170901'
files:
  - .gitignore
  - .package.yaml
  - config/inputs/add_files_from_inputs_disabled.dummy
  - config/inputs.disabled/js/00.doc.js
  - config/inputs.disabled/js/00.init.js
  - config/inputs.disabled/js/05.filesystemCount.js
  - config/inputs.disabled/js/07.logErrorAgg.js
  - config/inputs.disabled/js/09.filesystemcount.js
  - config/inputs.disabled/js/10.filesystem.js
  - config/inputs.disabled/js/10.filesystemcount.js
  - config/inputs.disabled/js/11.OSInfo.js
  - config/inputs.disabled/js/12.ShellCmd.js
  - config/inputs.disabled/js/13.ListDirFiles.js
  - config/inputs.disabled/js/22.fraud.snapshots.js
  - config/inputs.disabled/js/41.fms.rulestatus.js
  - config/inputs.disabled/yaml/01.ping.yaml
  - config/inputs.disabled/yaml/01.test.yaml
  - config/inputs.disabled/yaml/02.test.yaml
  - config/inputs.disabled/yaml/03.semaphores.yaml
  - config/inputs.disabled/yaml/04.db.appadm.yaml
  - config/inputs.disabled/yaml/09.memory.yaml
  - config/inputs.disabled/yaml/10.filesystemcount.fixed.yaml
  - config/inputs.disabled/yaml/10.filesystemcount.mobsubscribers.yaml
  - config/inputs.disabled/yaml/10.sessions.yaml
  - config/inputs.disabled/yaml/11.times.yaml
  - config/inputs.disabled/yaml/12.connections.yaml
  - config/move_files_from_the_disabled_folders.dummy
  - config/objects/nInput_AFPing.js
  - config/objects/nInput_CBPMSemaphores.js
  - config/objects/nInput_DB.js
  - config/objects/nInput_Filesystem.js
  - config/objects/nInput_FilesystemCount.js
  - config/objects/nInput_FMSRuleStatus.js
  - config/objects/nInput_IMMemory.js
  - config/objects/nInput_LogErrorAgg.js
  - config/objects/nInput_OSInfo.js
  - config/objects/nInput_RAIDMemory.js
  - config/objects/nInput_RunningFlows.js
  - config/objects/nInput_Semaphores.js
  - config/objects/nInput_Sessions.js
  - config/objects/nInput_Shell.js
  - config/objects/nOutput_Channels.js
  - config/objects/nOutput_EmailWarnings.js
  - config/objects/nOutput_H2.js
  - config/objects/nOutput_HTTP.js
  - config/objects/nOutput_HTTP_JSON.js
  - config/objects/nOutput_Log.js
  - config/objects/nOutput_Oracle.js
  - config/objects/nOutput_Stdout.js
  - config/objects/nValidation_AFPing.js
  - config/objects/nValidation_Semaphores.js
  - config/objects/nValidation_Yellows.js
  - config/objects.assets/noutputhttp/css/bootstrap-theme.min.css
  - config/objects.assets/noutputhttp/css/bootstrap.min.css
  - config/objects.assets/noutputhttp/css/font-awesome.min.css
  - config/objects.assets/noutputhttp/css/nattrmon.css
  - config/objects.assets/noutputhttp/dashboard.css
  - config/objects.assets/noutputhttp/fonts/fontawesome-webfont.eot
  - config/objects.assets/noutputhttp/fonts/fontawesome-webfont.svg
  - config/objects.assets/noutputhttp/fonts/fontawesome-webfont.ttf
  - config/objects.assets/noutputhttp/fonts/fontawesome-webfont.woff
  - config/objects.assets/noutputhttp/fonts/fontawesome-webfont.woff2
  - config/objects.assets/noutputhttp/fonts/FontAwesome.otf
  - config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.eot
  - config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.svg
  - config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.ttf
  - config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.woff
  - config/objects.assets/noutputhttp/history.html
  - config/objects.assets/noutputhttp/index.html
  - config/objects.assets/noutputhttp/js/angular-animate.min.js
  - config/objects.assets/noutputhttp/js/angular.min.js
  - config/objects.assets/noutputhttp/js/bootstrap.min.js
  - config/objects.assets/noutputhttp/js/holder.min.js
  - config/objects.assets/noutputhttp/js/ie10-viewport-bug-workaround.js
  - config/objects.assets/noutputhttp/js/jquery.min.js
  - config/objects.assets/noutputhttp/js/nattrmon_js.js
  - config/objects.assets/noutputhttp/js/retina.min.js
  - config/objects.assets/noutputhttp/now.html
  - config/outputs/add_files_from_outputs_disabled.dummy
  - config/outputs.disabled/0.init.js
  - config/outputs.disabled/1.h2output.js
  - config/outputs.disabled/1.oracleoutput.js
  - config/outputs.disabled/2.httpjson.js
  - config/outputs.disabled/3.http.js
  - config/outputs.disabled/4.logFile.js
  - config/outputs.disabled/5.emailWarnings.js
  - config/outputs.disabled/9.channels.js
  - config/outputs.disabled/yaml/02.httpjson.yaml
  - config/outputs.disabled/yaml/09.channels.yaml
  - config/validations/add_files_from_validations_disabled.dummy
  - config/validations.disabled/js/0.validatePing.js
  - config/validations.disabled/js/01.validatePing.js
  - config/validations.disabled/js/03.validateSemaphores.js
  - config/validations.disabled/js/04.validateErrorFlows.js
  - config/validations.disabled/js/30.validateYellows.js
  - config/validations.disabled/yaml/01.somebodyTouched.yaml
  - lib/nattribute.js
  - lib/nattributes.js
  - lib/nattributevalue.js
  - lib/ninput.js
  - lib/nmonitoredobject.js
  - lib/noutput.js
  - lib/nplug.js
  - lib/nvalidation.js
  - lib/nwarning.js
  - lib/nwarnings.js
  - nattrmon.js
  - README.md
  - tests/inputDBTest.yml
  - tests/inputShellTest.yml
  - tests/nattrmonTester.js
  - tests/outputTest.yml
  - tests/unitTest.js
  - tests/unitTestYAML.js
  - util/backupConfig.yaml
  - util/loadDB2Elastic.js
filesHash:
  .gitignore: 54e8786fc3ba63214d7f78bc82af2a0af2c00a57
  config/inputs/add_files_from_inputs_disabled.dummy: da39a3ee5e6b4b0d3255bfef95601890afd80709
  config/inputs.disabled/js/00.doc.js: 30076a2c9808fdf32de2c23dc5dcf3a995467e21
  config/inputs.disabled/js/00.init.js: 9b136327af5c67351b02e1d5b253f1ce0d9952a3
  config/inputs.disabled/js/05.filesystemCount.js: b63236a0fa5a2ed14930f8a2b359c5d1439fc195
  config/inputs.disabled/js/07.logErrorAgg.js: 46f522e3079ae9ba1fd6095bd44d53e602142282
  config/inputs.disabled/js/09.filesystemcount.js: e351abf60bf37268bd90a59ec6ad21ddcaa65796
  config/inputs.disabled/js/10.filesystem.js: 61d300a2961308a1bf3da2d763018469e632a5b8
  config/inputs.disabled/js/10.filesystemcount.js: a3031f5321f2ba20402093eeceebfd10d3474730
  config/inputs.disabled/js/11.OSInfo.js: a8cda4de91897cfe29485df98c472d13e0612b5c
  config/inputs.disabled/js/12.ShellCmd.js: a34d7727bfcd51819fc96e9f0c53ce91e02be613
  config/inputs.disabled/js/13.ListDirFiles.js: 2f997bc8695f76471c17f828d9d5a39708009510
  config/inputs.disabled/js/22.fraud.snapshots.js: f7c00b5410c107193734e4639c13a48a553edbc4
  config/inputs.disabled/js/41.fms.rulestatus.js: e0ea98c869241157591215a4b091858b1a651f9d
  config/inputs.disabled/yaml/01.ping.yaml: 4099ba54ccf9a1cf7468b832205a97c77de01065
  config/inputs.disabled/yaml/01.test.yaml: dff4e9f6b3fe72619b6f360901e8d2d76f93c6b0
  config/inputs.disabled/yaml/02.test.yaml: f933560ac567b06c6b08327ff54e1bf1da5ca093
  config/inputs.disabled/yaml/03.semaphores.yaml: 9b2b96bf067585976ea84a805e528fd796331782
  config/inputs.disabled/yaml/04.db.appadm.yaml: 21473f76bd120810c87adc6bc9c7f25b74c51261
  config/inputs.disabled/yaml/09.memory.yaml: abd00277facadf9fa16f230fcb92dfee48bcd527
  config/inputs.disabled/yaml/10.filesystemcount.fixed.yaml: 46d00308be67f3404eded27a536ae918d7f8c766
  config/inputs.disabled/yaml/10.filesystemcount.mobsubscribers.yaml: e375d9c5dcd2fe4360efcd6e6e9ceeff64432129
  config/inputs.disabled/yaml/10.sessions.yaml: 5a1724db9eca8b90a6bb6310948a00d7909fc555
  config/inputs.disabled/yaml/11.times.yaml: f437adf46690615e0b52b7cd36eba2ba0eb1cff2
  config/inputs.disabled/yaml/12.connections.yaml: 72579273a36487c4fb05b546f49bec649d8f245f
  config/move_files_from_the_disabled_folders.dummy: da39a3ee5e6b4b0d3255bfef95601890afd80709
  config/objects/nInput_AFPing.js: cb7b9bec10f4544a70799d86bcb1cc0d0c5d7b4b
  config/objects/nInput_CBPMSemaphores.js: e00ac4b176370dbd9ef0955d95580e7f167663a3
  config/objects/nInput_DB.js: d769641efd352f4e28dbe7368fce95e082763974
  config/objects/nInput_Filesystem.js: 12847a5ccb3d55915e9c40e6079db271788d4b46
  config/objects/nInput_FilesystemCount.js: d778859c05d909be5486933285ddce69f4e84ae2
  config/objects/nInput_FMSRuleStatus.js: 08faa5d4850734d896bae0970bb6834f8112d0b4
  config/objects/nInput_IMMemory.js: c5d709b7c0d2ff303412fc0bd0576c45e6933a52
  config/objects/nInput_LogErrorAgg.js: a609f966f5019420296f7c80fd3767442f60946e
  config/objects/nInput_OSInfo.js: b9405d7c3590bf6e31a3f4dd6fbfec95c2937f72
  config/objects/nInput_RAIDMemory.js: 4596222db4d95b5ec19f15447ed99871d4775374
  config/objects/nInput_RunningFlows.js: e6d04f533b3ad5c29182140985ebfaf28b05bfe0
  config/objects/nInput_Semaphores.js: 89e32953514a3251138c99f0b026581790522375
  config/objects/nInput_Sessions.js: ab2ae9a2312285e87a3dc1cb834885857ddf6c89
  config/objects/nInput_Shell.js: 38715894d7e6d5f01a9ad32c3dc0e9bbbb1fca0f
  config/objects/nOutput_Channels.js: d1ce6dcf85b7f889462b2b29bb3ad461ea5f028e
  config/objects/nOutput_EmailWarnings.js: d2e1754680e03fa60f517ec4b9f3a6a5ca442031
  config/objects/nOutput_H2.js: bdafc9cc58ea636d5afce850865f6317e44bf7f4
  config/objects/nOutput_HTTP.js: abb0f38277c693eeede3b4e5504eb7f5e4c229df
  config/objects/nOutput_HTTP_JSON.js: 86190db61678aa740bec0fa290fbb4bb8927debb
  config/objects/nOutput_Log.js: 5d319788dde09672659137eee86998a53dfde382
  config/objects/nOutput_Oracle.js: 93fa7228120945b1f1f6a7ecd8cf17853a4c6966
  config/objects/nOutput_Stdout.js: dadf1277ab262072e1154bc337db37006307f858
  config/objects/nValidation_AFPing.js: 305bee440a0f89855cc70d9fdaa90abfa39ec746
  config/objects/nValidation_Semaphores.js: 92ef1de7d2b1383594bab817723e8518650a45eb
  config/objects/nValidation_Yellows.js: 701c3ee77ca42d1853142c589e6a09bdd822108d
  config/objects.assets/noutputhttp/css/bootstrap-theme.min.css: c277f5dc2e08fa885e401ee367ac6c0eefa7a6dc
  config/objects.assets/noutputhttp/css/bootstrap.min.css: 12028adaae10f0c43445362df5481aeec8bb1153
  config/objects.assets/noutputhttp/css/font-awesome.min.css: 4c2c5f5f6cc86d775a44b944661e038b7be98149
  config/objects.assets/noutputhttp/css/nattrmon.css: f8a1827d3d8fd490023b8b472e3f8018af7e1d5a
  config/objects.assets/noutputhttp/dashboard.css: 9bab6b06cc427f9bd2908387e49e65f542c99764
  config/objects.assets/noutputhttp/fonts/fontawesome-webfont.eot: b3c2f08e73320135b69c23a3908b87a12053a2f6
  config/objects.assets/noutputhttp/fonts/fontawesome-webfont.svg: f346b8b3df147e4059e1a7d66c52c9a6e1cec3e8
  config/objects.assets/noutputhttp/fonts/fontawesome-webfont.ttf: 27cf1f2ec59aece6938c7bb2feb0e287ea778ff9
  config/objects.assets/noutputhttp/fonts/fontawesome-webfont.woff: 507970402e328b2baeb05bde73bf9ded4e2c3a2d
  config/objects.assets/noutputhttp/fonts/fontawesome-webfont.woff2: 574ea2698c03ae9477db2ea3baf460ee32f1a7ea
  config/objects.assets/noutputhttp/fonts/FontAwesome.otf: 0112e96f327d413938d37c1693806f468ffdbace
  config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.eot: 86b6f62b7853e67d3e635f6512a5a5efc58ea3c3
  config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.svg: 4dcf0ab896f5417047f881de91bad10dcbda48c6
  config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.ttf: 44bc1850f570972267b169ae18f1cb06b611ffa2
  config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.woff: 278e49a86e634da6f2a02f3b47dd9d2a8f26210f
  config/objects.assets/noutputhttp/history.html: 2bac092a0b8be121592109c148cd35599bf0c083
  config/objects.assets/noutputhttp/index.html: 0f2297867ba6ea919039fe44864148973b6af819
  config/objects.assets/noutputhttp/js/angular-animate.min.js: 48ceb01a73169491d532151456b4004cb13446d8
  config/objects.assets/noutputhttp/js/angular.min.js: d2e5e39be85f51c828be35b20d877f6b4c101add
  config/objects.assets/noutputhttp/js/bootstrap.min.js: e2ddfe5a574c29f39b511aada1bd85e0ba60fa70
  config/objects.assets/noutputhttp/js/holder.min.js: c1ad1dcfebf4c1770d40fc5d7bc46ca692d12822
  config/objects.assets/noutputhttp/js/ie10-viewport-bug-workaround.js: f580bb4a182612f728cdef6ab2fd5e417879980b
  config/objects.assets/noutputhttp/js/jquery.min.js: b63bd0a78caf8effb1061adcde124376de49c607
  config/objects.assets/noutputhttp/js/nattrmon_js.js: fc1858030689c16e07f73c8ae255b9c81e855215
  config/objects.assets/noutputhttp/js/retina.min.js: db4bf8404dbd9900faada058ba0fdfeaf6aab23b
  config/objects.assets/noutputhttp/now.html: 85a1c9e3b010fde950f3c21b5d99e428f1b296f7
  config/outputs/add_files_from_outputs_disabled.dummy: da39a3ee5e6b4b0d3255bfef95601890afd80709
  config/outputs.disabled/0.init.js: c7c7eed14977e210cd6973eed53cb42b1697a732
  config/outputs.disabled/1.h2output.js: 0bc642dce946dc17d6b0561d671e5030c0a89333
  config/outputs.disabled/1.oracleoutput.js: 825a9627256ffa7a7a12848387dd1d86b99ca8df
  config/outputs.disabled/2.httpjson.js: a5b47b16c4e6340a6bba1aedb344871f4e7289e4
  config/outputs.disabled/3.http.js: 35414c5895053e18788420e2ff17c9aa71c94eed
  config/outputs.disabled/4.logFile.js: 002c15afe1e2035dc77e626113bb6c935c2ecf57
  config/outputs.disabled/5.emailWarnings.js: ea8400db37cddda42ed276b75c94467e3239359a
  config/outputs.disabled/9.channels.js: 525092466a98774e9a5e3a184dde6f26953c46b9
  config/outputs.disabled/yaml/02.httpjson.yaml: 7c47a8c640dc9d8b8de10089ff2b90785d4eab9a
  config/outputs.disabled/yaml/09.channels.yaml: 5149e2ecb9fbb0884fe37dbb6e8ff6a0bd05243d
  config/validations/add_files_from_validations_disabled.dummy: da39a3ee5e6b4b0d3255bfef95601890afd80709
  config/validations.disabled/js/0.validatePing.js: 43b32c9c22d2285f0e14999956b45d07bc6d87b7
  config/validations.disabled/js/01.validatePing.js: 43b32c9c22d2285f0e14999956b45d07bc6d87b7
  config/validations.disabled/js/03.validateSemaphores.js: 1e8465015b49313b926cc58874def52b09fc59aa
  config/validations.disabled/js/04.validateErrorFlows.js: e56a93520e28d3f9b174264e3a199f9c2411d08b
  config/validations.disabled/js/30.validateYellows.js: e6f3ab2e0e870a0c7ac02e6d38603c187035f9e9
  config/validations.disabled/yaml/01.somebodyTouched.yaml: 18654e1a81a2af19e4c3cadb4dc086ca3f609f2e
  lib/nattribute.js: 4be29e971b5c0c23e1fc89f33d7ed6479d075809
  lib/nattributes.js: 4dc41e0d6fc25c1bdf16608ef41cad8d5df3506d
  lib/nattributevalue.js: f42b29f8b225a391cef31d7f3f22d41033aa3b96
  lib/ninput.js: af91b970f35098a561a187e93b7ec260d08ad934
  lib/nmonitoredobject.js: 24814b7ea819508162cac91a3dd7c14be801be96
  lib/noutput.js: 80983cb56a35eac3726a88e56cac9ea5d51cb39a
  lib/nplug.js: 5e5effd7342fdbc7600c2b283afcec01306d58fc
  lib/nvalidation.js: 8dc0019e337c4c0f12890b09ac5864b74175fd6c
  lib/nwarning.js: b6ab4c67c583f878c95bbf19ee11b7099c132136
  lib/nwarnings.js: 939a814f4eb4d114ef22785ed877eb2ffb165e8e
  nattrmon.js: 137ad8342b193e1888b64ad3ae84c95de68237b4
  README.md: b2a7dc80a439d865bd03d49960dbd6c96d02c254
  tests/inputDBTest.yml: acafbfa4233802897e81e9ee5457b06b76787303
  tests/inputShellTest.yml: 795c8479c1bfa93454b077d141f58161af5cae08
  tests/nattrmonTester.js: 0dc31695465dd13d73929a117e4d09a37be8d5fd
  tests/outputTest.yml: dade7c804e9f967eeb9016fcc045b943888b2ef0
  tests/unitTest.js: 54033b5beed0e7db52afe5449758cea3e969a6be
  tests/unitTestYAML.js: 891879cd3b71d0d6351ae09af0886f981937c6bf
  util/backupConfig.yaml: 3d34ced62d44180d2b95d075c68b31ce58f8e612
  util/loadDB2Elastic.js: caecf39b3afa1430c089ff57a9974d5bb10a06d9
