author: nuno.aguiar@wedotechnologies.com
scripts:
  posterase: ''
  postinstall: 'print(''AFPing: Since version 20160616 first parameter became URL.'');'
  preerase: ''
  preinstall: ''
keywords:
  - nattrmon
  - attribute
  - monitor
  - attrmon
bugs:
  url: 'http://192.168.40.110:8080/projects/nattrmon'
repository:
  type: http
  backupurl: 'http://172.25.1.32/svn/nAttrMon/trunk'
  url: 'http://192.168.40.110/svn/nAttrMon/trunk'
description: Tool for RAID and solution functional monitoring.
name: nAttrMon
main: nattrmon.js
mainJob: ''
license: WeDo internal only
version: '20170817'
dependencies:
  openaf: '>=20170701'
files:
  - .package.yaml
  - config/inputs/add_files_from_inputs_disabled.dummy
  - config/inputs.disabled/js/0.init.js
  - config/inputs.disabled/js/00.doc.js
  - config/inputs.disabled/js/00.init.js
  - config/inputs.disabled/js/01.ping.js
  - config/inputs.disabled/js/02.filesystem.js
  - config/inputs.disabled/js/03.cbpm.semaphores.js
  - config/inputs.disabled/js/03.semaphores.js
  - config/inputs.disabled/js/04.db.js
  - config/inputs.disabled/js/05.filesystemCount.js
  - config/inputs.disabled/js/06.errorFlows.js
  - config/inputs.disabled/js/06.runningFlows.js
  - config/inputs.disabled/js/07.logErrorAgg.js
  - config/inputs.disabled/js/08.RAIDmemory.js
  - config/inputs.disabled/js/09.filesystemcount.js
  - config/inputs.disabled/js/09.IMmemory.js
  - config/inputs.disabled/js/1.ping.js
  - config/inputs.disabled/js/10.filesystem.js
  - config/inputs.disabled/js/10.filesystemcount.js
  - config/inputs.disabled/js/11.OSInfo.js
  - config/inputs.disabled/js/12.ShellCmd.js
  - config/inputs.disabled/js/13.ListDirFiles.js
  - config/inputs.disabled/js/2.filesystem.js
  - config/inputs.disabled/js/22.fraud.snapshots.js
  - config/inputs.disabled/js/3.semaphores.js
  - config/inputs.disabled/js/4.db.js
  - config/inputs.disabled/js/41.fms.rulestatus.js
  - config/inputs.disabled/js/5.filesystemCount.js
  - config/inputs.disabled/js/6.errorFlows.js
  - config/inputs.disabled/js/6.runningFlows.js
  - config/inputs.disabled/js/7.logErrorAgg.js
  - config/inputs.disabled/js/8.RAIDmemory.js
  - config/inputs.disabled/js/9.filesystemcount.js
  - config/inputs.disabled/js/9.IMmemory.js
  - config/inputs.disabled/yaml/01.ping.yaml
  - config/inputs.disabled/yaml/01.test.yaml
  - config/inputs.disabled/yaml/02.test.yaml
  - config/inputs.disabled/yaml/03.semaphores.yaml
  - config/inputs.disabled/yaml/04.db.appadm.yaml
  - config/inputs.disabled/yaml/09.memory.yaml
  - config/inputs.disabled/yaml/10.filesystemcount.mobsubscribers.yaml
  - config/inputs.disabled/yaml/10.filesystemcount.nortel.yaml
  - config/inputs.disabled/yaml/10.sessions.yaml
  - config/inputs.disabled/yaml/11.times.yaml
  - config/inputs.disabled/yaml/12.connections.yaml
  - config/move_files_from_the_disabled_folders.dummy
  - config/objects/nInput_AFPing.js
  - config/objects/nInput_CBPMSemaphores.js
  - config/objects/nInput_DB.js
  - config/objects/nInput_Filesystem.js
  - config/objects/nInput_FilesystemCount.js
  - config/objects/nInput_FMSRuleStatus.js
  - config/objects/nInput_IMMemory.js
  - config/objects/nInput_LogErrorAgg.js
  - config/objects/nInput_OSInfo.js
  - config/objects/nInput_RAIDMemory.js
  - config/objects/nInput_RunningFlows.js
  - config/objects/nInput_Semaphores.js
  - config/objects/nInput_Sessions.js
  - config/objects/nInput_Shell.js
  - config/objects/nOutput_EmailWarnings.js
  - config/objects/nOutput_H2.js
  - config/objects/nOutput_HTTP.js
  - config/objects/nOutput_HTTP_JSON.js
  - config/objects/nOutput_Log.js
  - config/objects/nOutput_Oracle.js
  - config/objects/nOutput_Stdout.js
  - config/objects/nValidation_AFPing.js
  - config/objects/nValidation_Semaphores.js
  - config/objects/nValidation_Yellows.js
  - config/objects.assets/noutputhttp/css/bootstrap-theme.min.css
  - config/objects.assets/noutputhttp/css/bootstrap.min.css
  - config/objects.assets/noutputhttp/css/font-awesome.min.css
  - config/objects.assets/noutputhttp/css/nattrmon.css
  - config/objects.assets/noutputhttp/dashboard.css
  - config/objects.assets/noutputhttp/fonts/fontawesome-webfont.eot
  - config/objects.assets/noutputhttp/fonts/fontawesome-webfont.svg
  - config/objects.assets/noutputhttp/fonts/fontawesome-webfont.ttf
  - config/objects.assets/noutputhttp/fonts/fontawesome-webfont.woff
  - config/objects.assets/noutputhttp/fonts/fontawesome-webfont.woff2
  - config/objects.assets/noutputhttp/fonts/FontAwesome.otf
  - config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.eot
  - config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.svg
  - config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.ttf
  - config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.woff
  - config/objects.assets/noutputhttp/history.html
  - config/objects.assets/noutputhttp/index.html
  - config/objects.assets/noutputhttp/js/angular-animate.min.js
  - config/objects.assets/noutputhttp/js/angular.min.js
  - config/objects.assets/noutputhttp/js/bootstrap.min.js
  - config/objects.assets/noutputhttp/js/holder.min.js
  - config/objects.assets/noutputhttp/js/ie10-viewport-bug-workaround.js
  - config/objects.assets/noutputhttp/js/jquery.min.js
  - config/objects.assets/noutputhttp/js/nattrmon_js.js
  - config/objects.assets/noutputhttp/js/retina.min.js
  - config/objects.assets/noutputhttp/now.html
  - config/outputs/add_files_from_outputs_disabled.dummy
  - config/outputs.disabled/0.init.js
  - config/outputs.disabled/1.h2output.js
  - config/outputs.disabled/1.oracleoutput.js
  - config/outputs.disabled/2.httpjson.js
  - config/outputs.disabled/3.http.js
  - config/outputs.disabled/4.logFile.js
  - config/outputs.disabled/5.emailWarnings.js
  - config/outputs.disabled/9.channels.js
  - config/validations/add_files_from_validations_disabled.dummy
  - config/validations.disabled/0.validatePing.js
  - config/validations.disabled/01.somebodyTouched.yaml
  - config/validations.disabled/01.validatePing.js
  - config/validations.disabled/03.validateSemaphores.js
  - config/validations.disabled/04.validateErrorFlows.js
  - config/validations.disabled/3.validateSemaphores.js
  - config/validations.disabled/30.validateYellows.js
  - config/validations.disabled/4.validateErrorFlows.js
  - config/validations.disabled/yaml/01.somebodyTouched.yaml
  - lib/nattribute.js
  - lib/nattributes.js
  - lib/nattributevalue.js
  - lib/ninput.js
  - lib/nmonitoredobject.js
  - lib/noutput.js
  - lib/nplug.js
  - lib/nvalidation.js
  - lib/nwarning.js
  - lib/nwarnings.js
  - nattrmon.js
  - README.md
  - tests/inputDBTest.yml
  - tests/inputShellTest.yml
  - tests/nattrmonTester.js
  - tests/outputTest.yml
  - tests/unitTest.js
  - tests/unitTestYAML.js
  - util/loadDB2Elastic.js
filesHash:
  .package.yaml: 4e3761f5736fe320ea0e2b59ac70395461780e88
  config/inputs/add_files_from_inputs_disabled.dummy: da39a3ee5e6b4b0d3255bfef95601890afd80709
  config/inputs.disabled/js/0.init.js: 2563ccfc0a37d3be85f7485be88a08576fbb7f05
  config/inputs.disabled/js/00.doc.js: f03eb7b9bd36452d412d3668b0a4ef9c7605de65
  config/inputs.disabled/js/00.init.js: c6ff344e66b6621b75ff2bf138d4388d4ee38958
  config/inputs.disabled/js/01.ping.js: afdc4af84eb5b31611f285b6687d07574db321de
  config/inputs.disabled/js/02.filesystem.js: 25f17531a412ab24ecead4c50baec078f71f396b
  config/inputs.disabled/js/03.cbpm.semaphores.js: 5ef636830d4e64b3019fd03a8b7c5a0053943fe1
  config/inputs.disabled/js/03.semaphores.js: 4b237c7885f0797c99c15befb7afdf0f88f7ab63
  config/inputs.disabled/js/04.db.js: 827989c091e4f4fd9766c5c1e8fc7dff7c79b359
  config/inputs.disabled/js/05.filesystemCount.js: b63236a0fa5a2ed14930f8a2b359c5d1439fc195
  config/inputs.disabled/js/06.errorFlows.js: b6f370568fc578b55c8f1bfcc13235f05c9b8228
  config/inputs.disabled/js/06.runningFlows.js: 1f0aab01ac36a49775378f240e61b2ade7a8c8c8
  config/inputs.disabled/js/07.logErrorAgg.js: 46f522e3079ae9ba1fd6095bd44d53e602142282
  config/inputs.disabled/js/08.RAIDmemory.js: cf3694b307c1f0222e339e614ef43ac47a77b62c
  config/inputs.disabled/js/09.filesystemcount.js: 21ae3c36036bfaa0f786e73e9e862978727401df
  config/inputs.disabled/js/09.IMmemory.js: ae4ce8a4258c48ee4b9654a39d237fca73787fee
  config/inputs.disabled/js/1.ping.js: 504de317d9ad05c40bb3f0263f0896b19cba7a54
  config/inputs.disabled/js/10.filesystem.js: 23a492c93be89b7be4163169f581c28dd85ab502
  config/inputs.disabled/js/10.filesystemcount.js: a1ae5183c585f082779e403c5f4b87dcc2c3a0f6
  config/inputs.disabled/js/11.OSInfo.js: ff6d21332af1722b09a3cce062876a1b5e5b0eef
  config/inputs.disabled/js/12.ShellCmd.js: 9c5c85fa3b66d8dd760542683967efdd9b621d07
  config/inputs.disabled/js/13.ListDirFiles.js: 2f997bc8695f76471c17f828d9d5a39708009510
  config/inputs.disabled/js/2.filesystem.js: 25f17531a412ab24ecead4c50baec078f71f396b
  config/inputs.disabled/js/22.fraud.snapshots.js: f7c00b5410c107193734e4639c13a48a553edbc4
  config/inputs.disabled/js/3.semaphores.js: 4b237c7885f0797c99c15befb7afdf0f88f7ab63
  config/inputs.disabled/js/4.db.js: 827989c091e4f4fd9766c5c1e8fc7dff7c79b359
  config/inputs.disabled/js/41.fms.rulestatus.js: e0ea98c869241157591215a4b091858b1a651f9d
  config/inputs.disabled/js/5.filesystemCount.js: ad40ecfd93e56de59ae5014febc683b97f870386
  config/inputs.disabled/js/6.errorFlows.js: b6f370568fc578b55c8f1bfcc13235f05c9b8228
  config/inputs.disabled/js/6.runningFlows.js: 1f0aab01ac36a49775378f240e61b2ade7a8c8c8
  config/inputs.disabled/js/7.logErrorAgg.js: a4a39f1d07cc83af964d4b1068be91a74387a493
  config/inputs.disabled/js/8.RAIDmemory.js: cf3694b307c1f0222e339e614ef43ac47a77b62c
  config/inputs.disabled/js/9.filesystemcount.js: 21ae3c36036bfaa0f786e73e9e862978727401df
  config/inputs.disabled/js/9.IMmemory.js: ae4ce8a4258c48ee4b9654a39d237fca73787fee
  config/inputs.disabled/yaml/01.ping.yaml: 4099ba54ccf9a1cf7468b832205a97c77de01065
  config/inputs.disabled/yaml/01.test.yaml: dff4e9f6b3fe72619b6f360901e8d2d76f93c6b0
  config/inputs.disabled/yaml/02.test.yaml: f933560ac567b06c6b08327ff54e1bf1da5ca093
  config/inputs.disabled/yaml/03.semaphores.yaml: 9b2b96bf067585976ea84a805e528fd796331782
  config/inputs.disabled/yaml/04.db.appadm.yaml: 21473f76bd120810c87adc6bc9c7f25b74c51261
  config/inputs.disabled/yaml/09.memory.yaml: abd00277facadf9fa16f230fcb92dfee48bcd527
  config/inputs.disabled/yaml/10.filesystemcount.mobsubscribers.yaml: 1395ee8fc9596f2335090227af8c8abe743614c4
  config/inputs.disabled/yaml/10.filesystemcount.nortel.yaml: 41eeea5593b8bfe45b2f695111ce1e9006d1c81a
  config/inputs.disabled/yaml/10.sessions.yaml: 5a1724db9eca8b90a6bb6310948a00d7909fc555
  config/inputs.disabled/yaml/11.times.yaml: f437adf46690615e0b52b7cd36eba2ba0eb1cff2
  config/inputs.disabled/yaml/12.connections.yaml: 72579273a36487c4fb05b546f49bec649d8f245f
  config/move_files_from_the_disabled_folders.dummy: da39a3ee5e6b4b0d3255bfef95601890afd80709
  config/objects/nInput_AFPing.js: cb7b9bec10f4544a70799d86bcb1cc0d0c5d7b4b
  config/objects/nInput_CBPMSemaphores.js: 26b196dca733d8aed04b2f82ccb88ffd41583c97
  config/objects/nInput_DB.js: d769641efd352f4e28dbe7368fce95e082763974
  config/objects/nInput_Filesystem.js: c6f903bc4e7bee38bb948459abf60370a8e59ca0
  config/objects/nInput_FilesystemCount.js: d778859c05d909be5486933285ddce69f4e84ae2
  config/objects/nInput_FMSRuleStatus.js: 08faa5d4850734d896bae0970bb6834f8112d0b4
  config/objects/nInput_IMMemory.js: c5d709b7c0d2ff303412fc0bd0576c45e6933a52
  config/objects/nInput_LogErrorAgg.js: a609f966f5019420296f7c80fd3767442f60946e
  config/objects/nInput_OSInfo.js: b9405d7c3590bf6e31a3f4dd6fbfec95c2937f72
  config/objects/nInput_RAIDMemory.js: 4596222db4d95b5ec19f15447ed99871d4775374
  config/objects/nInput_RunningFlows.js: e6d04f533b3ad5c29182140985ebfaf28b05bfe0
  config/objects/nInput_Semaphores.js: 89e32953514a3251138c99f0b026581790522375
  config/objects/nInput_Sessions.js: 7beaca413ff50d4527371a980fe37ffc2bae6454
  config/objects/nInput_Shell.js: 38715894d7e6d5f01a9ad32c3dc0e9bbbb1fca0f
  config/objects/nOutput_EmailWarnings.js: d2e1754680e03fa60f517ec4b9f3a6a5ca442031
  config/objects/nOutput_H2.js: bdafc9cc58ea636d5afce850865f6317e44bf7f4
  config/objects/nOutput_HTTP.js: abb0f38277c693eeede3b4e5504eb7f5e4c229df
  config/objects/nOutput_HTTP_JSON.js: de4a4981164c43c2ed53b71a608ede5495cf93ba
  config/objects/nOutput_Log.js: 5d319788dde09672659137eee86998a53dfde382
  config/objects/nOutput_Oracle.js: 93fa7228120945b1f1f6a7ecd8cf17853a4c6966
  config/objects/nOutput_Stdout.js: dadf1277ab262072e1154bc337db37006307f858
  config/objects/nValidation_AFPing.js: 305bee440a0f89855cc70d9fdaa90abfa39ec746
  config/objects/nValidation_Semaphores.js: 97b6c1850b80d95cc92c1c50b05fdfa26467fd94
  config/objects/nValidation_Yellows.js: 942478fcd710e392add0b6ef6349ef51a895b764
  config/objects.assets/noutputhttp/css/bootstrap-theme.min.css: fc6b4268fbd57ad95d2b41a1d4d6866f222fbdb2
  config/objects.assets/noutputhttp/css/bootstrap.min.css: ed29315e0ffb3f14382431f2724235bf67f44eb3
  config/objects.assets/noutputhttp/css/font-awesome.min.css: 05ea25bc9b3ac48993e1fee322d3bc94b49a6e22
  config/objects.assets/noutputhttp/css/nattrmon.css: f8a1827d3d8fd490023b8b472e3f8018af7e1d5a
  config/objects.assets/noutputhttp/dashboard.css: 96d9d77e456868b0797afe0ce344be026315d535
  config/objects.assets/noutputhttp/fonts/fontawesome-webfont.eot: b3c2f08e73320135b69c23a3908b87a12053a2f6
  config/objects.assets/noutputhttp/fonts/fontawesome-webfont.svg: 2b3c8ba7008cc014d8fb37abc6f9f49aeda83824
  config/objects.assets/noutputhttp/fonts/fontawesome-webfont.ttf: 27cf1f2ec59aece6938c7bb2feb0e287ea778ff9
  config/objects.assets/noutputhttp/fonts/fontawesome-webfont.woff: 507970402e328b2baeb05bde73bf9ded4e2c3a2d
  config/objects.assets/noutputhttp/fonts/fontawesome-webfont.woff2: 574ea2698c03ae9477db2ea3baf460ee32f1a7ea
  config/objects.assets/noutputhttp/fonts/FontAwesome.otf: 0112e96f327d413938d37c1693806f468ffdbace
  config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.eot: 86b6f62b7853e67d3e635f6512a5a5efc58ea3c3
  config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.svg: de51a8494180a6db074af2dee2383f0a363c5b08
  config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.ttf: 44bc1850f570972267b169ae18f1cb06b611ffa2
  config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.woff: 278e49a86e634da6f2a02f3b47dd9d2a8f26210f
  config/objects.assets/noutputhttp/history.html: aac6be153b65c31424a2b0e33b772b2e129fe76b
  config/objects.assets/noutputhttp/index.html: c454af426dc25960d1a2992b6cac99e11881ea48
  config/objects.assets/noutputhttp/js/angular-animate.min.js: 648e2ca79c0c074b2b61042e91d31b353ad290d3
  config/objects.assets/noutputhttp/js/angular.min.js: d0e3fccc46957eeaaf5611075a2015b410b64725
  config/objects.assets/noutputhttp/js/bootstrap.min.js: 253711c6d825de55a8360552573be950da180614
  config/objects.assets/noutputhttp/js/holder.min.js: c1ad1dcfebf4c1770d40fc5d7bc46ca692d12822
  config/objects.assets/noutputhttp/js/ie10-viewport-bug-workaround.js: b133cb4aaff8f32026190281d8a27456eace82b1
  config/objects.assets/noutputhttp/js/jquery.min.js: 7ed710bf2b3a08cee23950790208683b0346fb1c
  config/objects.assets/noutputhttp/js/nattrmon_js.js: fc1858030689c16e07f73c8ae255b9c81e855215
  config/objects.assets/noutputhttp/js/retina.min.js: da44a409a0907960a6526cf35807ecaf61059223
  config/objects.assets/noutputhttp/now.html: 8dc28c8f998a319561567c342aa46fc16974e459
  config/outputs/add_files_from_outputs_disabled.dummy: da39a3ee5e6b4b0d3255bfef95601890afd80709
  config/outputs.disabled/0.init.js: c7c7eed14977e210cd6973eed53cb42b1697a732
  config/outputs.disabled/1.h2output.js: 0bc642dce946dc17d6b0561d671e5030c0a89333
  config/outputs.disabled/1.oracleoutput.js: 825a9627256ffa7a7a12848387dd1d86b99ca8df
  config/outputs.disabled/2.httpjson.js: a5b47b16c4e6340a6bba1aedb344871f4e7289e4
  config/outputs.disabled/3.http.js: 35414c5895053e18788420e2ff17c9aa71c94eed
  config/outputs.disabled/4.logFile.js: 002c15afe1e2035dc77e626113bb6c935c2ecf57
  config/outputs.disabled/5.emailWarnings.js: 4a0139aabd64a3c56c1842499dd6d2203f607550
  config/outputs.disabled/9.channels.js: fd411e585f542586b77d61afcce668980f8c0207
  config/validations/add_files_from_validations_disabled.dummy: da39a3ee5e6b4b0d3255bfef95601890afd80709
  config/validations.disabled/0.validatePing.js: cc572c157971ebdccd0a40a261f199cb9e509b5c
  config/validations.disabled/01.somebodyTouched.yaml: 2d6a2c34c39aec49d9126c6304e04e66b978a26a
  config/validations.disabled/01.validatePing.js: cc572c157971ebdccd0a40a261f199cb9e509b5c
  config/validations.disabled/03.validateSemaphores.js: 6ded3ea530db8b5d4621fa8bad510e281ebd632d
  config/validations.disabled/04.validateErrorFlows.js: 9b7ff4c1cd03fe47082107d2c22250be1d45a2b4
  config/validations.disabled/3.validateSemaphores.js: c7559585a324bcb41a9d809446b8a448178d947c
  config/validations.disabled/30.validateYellows.js: 7a99fcd5e3728805783c5c18aff97488f3aed5d7
  config/validations.disabled/4.validateErrorFlows.js: 9b7ff4c1cd03fe47082107d2c22250be1d45a2b4
  config/validations.disabled/yaml/01.somebodyTouched.yaml: 2d6a2c34c39aec49d9126c6304e04e66b978a26a
  lib/nattribute.js: 4be29e971b5c0c23e1fc89f33d7ed6479d075809
  lib/nattributes.js: dd6a45d31c59dc82099f3f4a79694d719dc8b207
  lib/nattributevalue.js: f42b29f8b225a391cef31d7f3f22d41033aa3b96
  lib/ninput.js: af91b970f35098a561a187e93b7ec260d08ad934
  lib/nmonitoredobject.js: 24814b7ea819508162cac91a3dd7c14be801be96
  lib/noutput.js: 80983cb56a35eac3726a88e56cac9ea5d51cb39a
  lib/nplug.js: 5295a76feed0d3f437e858e014f512db9de29d84
  lib/nvalidation.js: 8dc0019e337c4c0f12890b09ac5864b74175fd6c
  lib/nwarning.js: b6ab4c67c583f878c95bbf19ee11b7099c132136
  lib/nwarnings.js: a4ee099079507c78c2610504171bff1ab6a5056e
  nattrmon.js: ff0604b8fd981dc93ff01f0b891340d112db36ef
  README.md: 577a767a71b1dd79d120204da1bc18b0f2b18d25
  tests/inputDBTest.yml: c38616606dc5956e449189d11f8e661170f94dfb
  tests/inputShellTest.yml: ce643955982cb16b53a8843acd3549466e5cddf5
  tests/nattrmonTester.js: 228472c2b83fbc11688a6d25a0d97165f78b4883
  tests/outputTest.yml: 0c4ba4176163e4aa9ff7fd4ae4128339d8384581
  tests/unitTest.js: 54033b5beed0e7db52afe5449758cea3e969a6be
  tests/unitTestYAML.js: 215400bf5e21fbb27f507c2e10b1e75f290e8ff2
  util/loadDB2Elastic.js: caecf39b3afa1430c089ff57a9974d5bb10a06d9
