input:
   - name         : Flows in error
     cron         : "*/2 * * * * *"
     onlyOnEvent  : true
     waitForFinish: true
     execFrom     : nInput_CBPMRunningFlows
     execArgs     :
       chKeys      : raidServers
       status      : ERROR
       hoursToCheck: 120
       attrTemplate: Flows/Flows errors

   - name         : Flows running
     cron         : "*/2 * * * * *"
     onlyOnEvent  : true
     waitForFinish: true
     execFrom     : nInput_CBPMRunningFlows
     execArgs     :
       chKeys      : raidServers
       status      : STARTED
       hoursToCheck: 120
       attrTemplate: Flows/Flows running     