input: 	
   name         : Mobile Subscribers Filesystem check 
   timeInterval : 60000
   waitForFinish: true
   onlyOnEvent  : true
   execFrom     : nInput_FilesystemCount
   execArgs     : 
     attrTemplate: Filesystem/Mobile Subscribers
     folders     :
      - name   : Received
        folder : /opt/wedo/data/loading/reference/mobile_subscribers/subscriber/received
        pattern: .*
      - name   : Input
        folder : /opt/wedo/data/loading/reference/mobile_subscribers/subscriber/in
        pattern: .*
      - name   : Error
        folder : /opt/wedo/data/loading/reference/mobile_subscribers/subscriber/err
        pattern: .*
      - name   : Done
        folder : /opt/wedo/data/loading/reference/mobile_subscribers/subscriber/done
        pattern: .*
